title: Jincheng Li's Homepage
page-top-title: 李金澄
top-section-bg-text: Live a life you'll remember.
home-subtitle: A personal website of Jincheng Li.
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
